
[network-architecture]

### Select only one of the following architectures to be true.
Apply_CNN_architecture                               = true
Apply_3D_CNN_architecture                            = false


[network-architecture.CNN-architecture]

CovLayer_padding_mode                                 = 'reflect'    # 'replicate' or 'reflect' or 'zeros' or 'circular'
Pooling_padding_mode                                  = 'reflect' # 'replicate' or 'reflect' or 'constant' or 'circular'

ResNet.Settings                                      = true
ResNet.Blocks                                        = 'BasicBlock'
ResNet.blocks_num                                    = [2,2,2,2]
ResNet.Pooling_layer_type                            = 'MaxPooling2d' # 'MaxPooling2d' or 'AvgPooling2d'
############# Two Combine Models; Classified by variables
TwoCombineModels.Settings                             = false # Only Available to ResNet and ResNet_MLP; one of those two structures settings must be true.
TwoCombineModels.Variable                             = 'GeoPM25'
TwoCombineModels.threshold                            = 4.0

#############

ResNet_MLP.Settings                                   = false
ResNet_MLP.Blocks                                     = 'Bottleneck'
ResNet_MLP.blocks_num                                 = [1,1,1,1]

#############

ResNet_Classification.Settings                        = false
ResNet_Classification.Blocks                          = 'BasicBlock'
ResNet_Classification.blocks_num                      = [1,1,0,1]
ResNet_Classification.left_bin                        = -5.0
ResNet_Classification.right_bin                       = 5.0
ResNet_Classification.bins_number                     = 101

#############
ResNet_MultiHeadNet.Settings                          = false
ResNet_MultiHeadNet.Blocks                            = 'BasicBlock'
ResNet_MultiHeadNet.blocks_num                        = [1,1,0,1]
ResNet_MultiHeadNet.left_bin                          = -5.0
ResNet_MultiHeadNet.right_bin                         = 5.0
ResNet_MultiHeadNet.bins_number                       = 101
ResNet_MultiHeadNet.regression_portion                = 0.5
ResNet_MultiHeadNet.classifcation_portion             = 0.5

#############
LateFusion.Settings                                   = false
LateFusion.Blocks                                     = 'Bottleneck'
LateFusion.blocks_num                                 = [1,1,1,1]
LateFusion.initial_channels                           = ['AOD', 'EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias',  'GeoPM25','ETA',
                                                       'GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS',
                                                       'NA_CNN_PM25',#'GL_CNN_PM25',#
                                                       'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT',
                                                       'NH3_anthro_emi','NO_anthro_emi','SO2_anthro_emi', #'OC_anthro_emi', 'BC_anthro_emi', 'N2O_anthro_emi','NMVOC_anthro_emi',
                                                       'DST_offline_emi', 'SSLT_offline_emi',
                                                       'RH', 'T2M', 'U10M', 'V10M','PRECTOT','PBLH', 
                                                       'Urban_Builtup_Lands',#'Croplands','Crop_Nat_Vege_Mos', #'Permanent_Wetlands', 
                                                    
                                                       ] 
LateFusion.LateFusion_channels                         = ['Lat', 'Lon','elevation','Month_of_Year',]

#############
MultiHeadLateFusion.Settings                           = false
MultiHeadLateFusion.Blocks                             = 'BasicBlock'
MultiHeadLateFusion.blocks_num                         = [1,1,1,1]
MultiHeadLateFusion.initial_channels                   = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                                                        'GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS',
                                                        'NA_CNN_PM25',#'GL_CNN_PM25'
                                                        'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT',
                                                        'NH3_anthro_emi','SO2_anthro_emi', 'NO_anthro_emi',#'OC_anthro_emi', 'BC_anthro_emi',  # 'N2O_anthro_emi','NMVOC_anthro_emi',
                                                        'DST_offline_emi', 'SSLT_offline_emi',
                                                        'PBLH', 'RH', 'T2M', 'U10M', 'V10M','PRECTOT',
                                                        'Urban_Builtup_Lands',# 'Croplands',#'Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 
                                                       #,#'S1','S2','S3',' 
                                                        #'Population'
                                                       ]               
MultiHeadLateFusion.LateFusion_channels                = [ 'Lat', 'Lon','elevation','Month_of_Year', ]
MultiHeadLateFusion.left_bin                           = -10.0
MultiHeadLateFusion.right_bin                          = 10.0
MultiHeadLateFusion.bins_number                        = 201
MultiHeadLateFusion.regression_portion                 = 0.5
MultiHeadLateFusion.classifcation_portion              = 0.5



[network-architecture.CNN3D-architecture]

CovLayer_padding_mode_3D                                = 'replicate'    # 'replicate' or 'reflect' or 'zeros' or 'circular'
Pooling_padding_mode_3D                                 = 'replicate' # 'replicate' or 'reflect' or 'constant' or 'circular'

ResNet3D.Settings                                       = true
ResNet3D.Blocks                                         = 'BasicBlock'
ResNet3D.blocks_num                                     = [2,2,2,2]
ResNet3D.output_channels                                = [64,128,256,512]
ResNet3D.Pooling_layer_type_3D                          = 'MaxPooling3d' # 'MaxPooling3d' or 'AvgPooling3d' or 'None'
ResNet3D.Depth                                          = 3

#########################################################################################################################################################
